- name: variable in ansible
  hosts: mongodb
  vars:
   COURSE: devops
   TRAINER: vinay
   DURATION: 60HRS
  tasks:
  - name: print hello world
    ansible.builtin.debug:
     msg: "Hello i am learning devops" 
  - name: print in variables
    ansible.builtin.debug:
     msg: "i am learning {{COURSE}}, trainer is {{TRAINER}}, duration is {{DURATION}}"   