- name: variables at task level
  host: localhost
  vars:
  - money: "10000"
    land: "100 Arc"
  tasks:
  - name: inherit values from play
    ansible.builtin.debug:
     msg: "MONEY: {{money}}, LAND: {{land}}"
  - name: inherit values from play and add values
    vars:
    - money: "2000000"
      houses: "3 houses"
    ansible.builtin.debug:
     msg: "MONEY: {{money}}, LAND: {{land}}, HOUSES: {{houses}}"
     
            