- name: ansible variable datatypes
  hosts: localhost
  vars:
  - age: 30  #Number
  - NAME: "raj" #string
  - isDevops: true  #Boolean
  - Skills:
    - Devops
    - AWS
    - Docker

  - Experience:
    Devops: 7
    AWS: 5
    Docler: 4
  tasks:
  - name: print number variable
    ansible.builtin.debug:
     msg: "{{age}}"
  - name: print string variable
    ansible.builtin.debug:
     msg: "{{NAME}}"
  - name: print boolean variable
    ansible.builtin.debug:
     msg: "{{isDevops}}"
  - name: print list variables
    ansible.builtin.debug:
     msg: "{{Skills}}"
  - name: print map variables
    ansible.builtin.debug:
     msg: "{{Experience}}"            
