- name: install packages
  hosts: mogodb
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.yum:
     name: "{{item}}"
     state: installed
    loop:
    - nginx
    - postfix
     